import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils/trpc';
import { signIn, signOut, useSession } from 'next-auth/react';
import { Flex, Heading, VStack } from '@chakra-ui/react';

const Home: NextPage = () => {
  const { data } = trpc.example.hello.useQuery({ text: 'World' });

  return (
    <>
      <Head>
        <title>Oumla Onboarding</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Flex height='100vh' justifyContent='center' alignItems='center'>
        <VStack>
          <Heading>{data && data.greeting}</Heading>
        </VStack>
      </Flex>
    </>
  );
};

export default Home;
